<?php

namespace Bookshop\BookshopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CartItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookshopOrderRepository extends EntityRepository 
{

    public function getRecent($userID) 
    {
        $qb = $this->createQueryBuilder('l')
                ->select('l')->orderBy('l.id', 'desc')
                ->where('l.user = :userID')
                ->setParameter("userID", $userID);

        return $qb->getQuery()
                        ->getResult();
    }
    public function getRecentNr($userID,$nr) 
    {
        $qb = $this->createQueryBuilder('l')
                ->select('l')->orderBy('l.id', 'desc')
                ->where('l.user = :userID')
                ->setParameter("userID", $userID)
                ->setMaxResults($nr);

        return $qb->getQuery()
                        ->getResult();
    }

}
