<?php

namespace Bookshop\BookshopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CartItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartItemsRepository extends EntityRepository {

    public function getItems($cartid) {
        $qb = $this->createQueryBuilder('i')
                ->select('i')->where('i.cartId = :cartid')
                ->setParameter('cartid', $cartid)
                ->addOrderBy('i.id', 'desc');

        return $qb->getQuery()
                        ->getResult();
    }

    public function getCartItem($productid,$cartid) {
        $qb = $this->createQueryBuilder('p')
                ->select('p')->where('p.cartId = :cartid and p.productId = :productid')
                ->setParameter('cartid', $cartid)
                ->setParameter('productid', $productid);

        return $qb->getQuery()
                        ->getResult();
    }

}
