<?php

namespace Bookshop\BookshopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ImageRepository extends EntityRepository
{
    
    public function getImage(){
        $qb = $this->createQueryBuilder('c')
                ->select('c');
        
        return $qb->getQuery()->getResult();
    }
}
