<?php

namespace Bookshop\BookshopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CartItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository 
{

    public function getUsers() 
    {   
        $em = $this->getEntityManager();
        $dql = "SELECT u FROM BookshopBookshopBundle:User u WHERE u.roles not like '%ROLE_SUPER_ADMIN%'";
        $query = $em->createQuery($dql);
        return $query;
    }

}
