bookshop_admin_homepage:
    pattern:  /
    defaults: { _controller: BookshopAdminBundle:Default:index }

bookshop_admin_user:
  resource:   "@BookshopAdminBundle/Resources/config/routing/user/routing.yml"
  prefix:     /user

bookshop_admin_product:
  resource: "@BookshopAdminBundle/Resources/config/routing/product/routing.yml"
  prefix:   /product

bookshop_admin_order:
  resource: "@BookshopAdminBundle/Resources/config/routing/order/routing.yml"
  prefix:   /order 