bookshop_admin_order_list:
  pattern:  /
  defaults: { _controller: BookshopAdminBundle:OrderAdmin:index }
bookshop_admin_order_set_status:
  pattern:  /{id}/{stateId}
  defaults: { _controller: BookshopAdminBundle:OrderAdmin:setState }